// Code generated by scripts/build-go-bindings.mjs. DO NOT EDIT.
// Source: specs/vta/attestation/status/0.1/payload.schema.json

package vtaattestationstatusv0_1

import (
	"encoding/json"
	"github.com/trustoverip/dtgwg-trust-tasks-tf/trust-tasks-go/trusttasks"
)

// ResponseTeeType The platform whose evidence vta/attestation/report returns: nitro (AWS
// Nitro Enclaves), sev-snp (AMD SEV-SNP), or simulated (a development build whose
// evidence no verifier should accept).
type ResponseTeeType string

// Values ResponseTeeType may take, per this specification's schema.
const (
	ResponseTeeTypeNitro     ResponseTeeType = "nitro"
	ResponseTeeTypeSevSnp    ResponseTeeType = "sev-snp"
	ResponseTeeTypeSimulated ResponseTeeType = "simulated"
)

// Response VTA Attestation Status — response payload
type Response struct {
	// The platform whose evidence vta/attestation/report returns: nitro (AWS Nitro Enclaves),
	// sev-snp (AMD SEV-SNP), or simulated (a development build whose evidence no verifier
	// should accept).
	TeeType ResponseTeeType `json:"teeType"`

	// Whether the agent found the platform at boot. False means it was configured for one it
	// did not find, and it produces no evidence.
	Detected bool `json:"detected"`

	// The platform's own version string, when it reports one. Informational.
	PlatformVersion *string `json:"platformVersion,omitempty"`

	// Ecosystem-defined extension members per SPEC.md §4.5.1.
	Ext *Ext `json:"ext,omitempty"`
}

// Ext Vendor-namespaced extension object per SPEC.md §4.5.1. Each immediate key MUST be a
// reverse-DNS namespace; structure under each namespace is opaque to the framework.
type Ext = map[string]json.RawMessage

// Payload Asks an agent which trusted execution environment it runs in. The payload
// carries nothing. The outer document members (id, type, issuer, recipient, issuedAt,
// expiresAt, proof) are owned by the framework — SPEC §6.3.
type Payload struct {
	// Ecosystem-defined extension members per SPEC.md §4.5.1.
	Ext *Ext `json:"ext,omitempty"`
}

// TypeURI is the Trust Task type URI this package's Payload is carried under.
const TypeURI = "https://trusttasks.org/spec/vta/attestation/status/0.1"

// ResponseTypeURI is the success-response form of TypeURI (SPEC §4.4.1).
const ResponseTypeURI = "https://trusttasks.org/spec/vta/attestation/status/0.1#response"

// PayloadSchemaJSON is this specification's payload schema, as JSON text.
//
// SPEC §7.2 item 2 is performed against this. It ships with the package rather
// than only as a file under specs/ because a Go struct carries none of the
// schema's constraints — not minLength, not pattern, not the oneOf mutual
// exclusion — so without it every such rule is unenforced. Cross-file $refs are
// already inlined, so it needs no resolver.
const PayloadSchemaJSON = "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"$id\":\"https://trusttasks.org/spec/vta/attestation/status/0.1\",\"title\":\"VTA Attestation — Status — payload\",\"description\":\"Asks an agent which trusted execution environment it runs in. The payload carries nothing. The outer document members (id, type, issuer, recipient, issuedAt, expiresAt, proof) are owned by the framework — SPEC §6.3.\",\"type\":\"object\",\"additionalProperties\":false,\"properties\":{\"ext\":{\"$ref\":\"#/$defs/Ext\",\"description\":\"Ecosystem-defined extension members per SPEC.md §4.5.1.\"}},\"$defs\":{\"Response\":{\"$anchor\":\"response\",\"title\":\"VTA Attestation Status — response payload\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"teeType\",\"detected\"],\"properties\":{\"teeType\":{\"type\":\"string\",\"enum\":[\"nitro\",\"sev-snp\",\"simulated\"],\"description\":\"The platform whose evidence vta/attestation/report returns: nitro (AWS Nitro Enclaves), sev-snp (AMD SEV-SNP), or simulated (a development build whose evidence no verifier should accept).\"},\"detected\":{\"type\":\"boolean\",\"description\":\"Whether the agent found the platform at boot. False means it was configured for one it did not find, and it produces no evidence.\"},\"platformVersion\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":256,\"description\":\"The platform's own version string, when it reports one. Informational.\"},\"ext\":{\"$ref\":\"#/$defs/Ext\",\"description\":\"Ecosystem-defined extension members per SPEC.md §4.5.1.\"}}},\"Ext\":{\"title\":\"Ext\",\"description\":\"Vendor-namespaced extension object per SPEC.md §4.5.1. Each immediate key MUST be a reverse-DNS namespace; structure under each namespace is opaque to the framework.\",\"type\":\"object\",\"minProperties\":1,\"additionalProperties\":true,\"propertyNames\":{\"pattern\":\"^[a-z][a-z0-9-]*(\\\\.[a-z0-9-]+)+$\"}}}}"

// ResponsePayloadSchemaJSON is PayloadSchemaJSON for the success-response variant.
const ResponsePayloadSchemaJSON = "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"$ref\":\"#/$defs/Response\",\"$defs\":{\"Response\":{\"$anchor\":\"response\",\"title\":\"VTA Attestation Status — response payload\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"teeType\",\"detected\"],\"properties\":{\"teeType\":{\"type\":\"string\",\"enum\":[\"nitro\",\"sev-snp\",\"simulated\"],\"description\":\"The platform whose evidence vta/attestation/report returns: nitro (AWS Nitro Enclaves), sev-snp (AMD SEV-SNP), or simulated (a development build whose evidence no verifier should accept).\"},\"detected\":{\"type\":\"boolean\",\"description\":\"Whether the agent found the platform at boot. False means it was configured for one it did not find, and it produces no evidence.\"},\"platformVersion\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":256,\"description\":\"The platform's own version string, when it reports one. Informational.\"},\"ext\":{\"$ref\":\"#/$defs/Ext\",\"description\":\"Ecosystem-defined extension members per SPEC.md §4.5.1.\"}}},\"Ext\":{\"title\":\"Ext\",\"description\":\"Vendor-namespaced extension object per SPEC.md §4.5.1. Each immediate key MUST be a reverse-DNS namespace; structure under each namespace is opaque to the framework.\",\"type\":\"object\",\"minProperties\":1,\"additionalProperties\":true,\"propertyNames\":{\"pattern\":\"^[a-z][a-z0-9-]*(\\\\.[a-z0-9-]+)+$\"}}}}"

// Spec is the SPEC §7.2 policy for the request variant, taken from this
// specification's front matter. Pass it to trusttasks.ConsumeInbound — items 5b,
// 7 and 8 are per-specification and cannot be derived from the document alone,
// and item 2 needs the schema it carries.
var Spec = trusttasks.SpecPolicy{
	TypeURI:             TypeURI,
	IsBearer:            false,
	IsProofRequired:     false,
	IsRecipientRequired: true,
	IsIssuedAtRequired:  false,
	PayloadSchema:       PayloadSchemaJSON,
}

// ResponseSpec is the SPEC §7.2 policy for the success-response variant.
// IsRecipientRequired tracks the *issuer* party's requirement, because a response
// swaps the parties (§7.3 item 5).
var ResponseSpec = trusttasks.SpecPolicy{
	TypeURI:             ResponseTypeURI,
	IsBearer:            false,
	IsProofRequired:     true,
	IsRecipientRequired: true,
	IsIssuedAtRequired:  false,
	PayloadSchema:       ResponsePayloadSchemaJSON,
}
