// Code generated by scripts/build-dart-bindings.mjs. DO NOT EDIT.
// Source: specs/vta/attestation/status/0.1/payload.schema.json

import 'package:trust_tasks/trust_tasks.dart';

/// Vendor-namespaced extension object per SPEC.md §4.5.1. Each immediate key MUST be a
/// reverse-DNS namespace; structure under each namespace is opaque to the framework.
typedef Ext = Map<String, dynamic>;

/// The platform whose evidence vta/attestation/report returns: nitro (AWS Nitro
/// Enclaves), sev-snp (AMD SEV-SNP), or simulated (a development build whose evidence
/// no verifier should accept).
///
/// An extension type rather than an enum: a value from a newer MINOR of this
/// specification must not crash the parse (SPEC §5.2), and an enum would throw on one.
/// Compare against the constants below, and treat anything else as unrecognised.
extension type const ResponseTeeType(String value) {
  static const ResponseTeeType nitro = ResponseTeeType('nitro');
  static const ResponseTeeType sevSnp = ResponseTeeType('sev-snp');
  static const ResponseTeeType simulated = ResponseTeeType('simulated');

  /// Every value this specification's schema permits.
  static const List<ResponseTeeType> values = <ResponseTeeType>[
    nitro,
    sevSnp,
    simulated
  ];
}

/// VTA Attestation Status — response payload
class Response {
  const Response({
    required this.teeType,
    required this.detected,
    this.platformVersion,
    this.ext,
  });

  /// Read this payload from a decoded JSON object.
  factory Response.fromJson(Map<String, dynamic> json) => Response(
        teeType: ResponseTeeType(json['teeType'] as String),
        detected: json['detected'] as bool,
        platformVersion: json['platformVersion'] as String?,
        ext: json['ext'] as Map<String, dynamic>?,
      );

  /// The platform whose evidence vta/attestation/report returns: nitro (AWS Nitro
  /// Enclaves), sev-snp (AMD SEV-SNP), or simulated (a development build whose evidence
  /// no verifier should accept).
  final ResponseTeeType teeType;

  /// Whether the agent found the platform at boot. False means it was configured for one
  /// it did not find, and it produces no evidence.
  final bool detected;

  /// The platform's own version string, when it reports one. Informational.
  final String? platformVersion;

  /// Ecosystem-defined extension members per SPEC.md §4.5.1.
  final Ext? ext;

  /// Serialize to a JSON-encodable map, omitting absent members.
  Map<String, dynamic> toJson() => <String, dynamic>{
        'teeType': teeType.value,
        'detected': detected,
        if (platformVersion != null) 'platformVersion': platformVersion!,
        if (ext != null) 'ext': ext!,
      };
}

/// Asks an agent which trusted execution environment it runs in. The payload carries
/// nothing. The outer document members (id, type, issuer, recipient, issuedAt,
/// expiresAt, proof) are owned by the framework — SPEC §6.3.
class Payload {
  const Payload({
    this.ext,
  });

  /// Read this payload from a decoded JSON object.
  factory Payload.fromJson(Map<String, dynamic> json) => Payload(
        ext: json['ext'] as Map<String, dynamic>?,
      );

  /// Ecosystem-defined extension members per SPEC.md §4.5.1.
  final Ext? ext;

  /// Serialize to a JSON-encodable map, omitting absent members.
  Map<String, dynamic> toJson() => <String, dynamic>{
        if (ext != null) 'ext': ext!,
      };
}

/// The Trust Task type URI this library's [Payload] is carried under.
const String typeUri = 'https://trusttasks.org/spec/vta/attestation/status/0.1';

/// The success-response form of [typeUri] (SPEC §4.4.1).
const String responseTypeUri =
    'https://trusttasks.org/spec/vta/attestation/status/0.1#response';

/// This specification's payload schema, as JSON text.
///
/// SPEC §7.2 item 2 is performed against this. It ships with the library rather
/// than only as a file under specs/ because a Dart class carries none of the
/// schema's constraints — not minLength, not pattern, not the oneOf mutual
/// exclusion — so without it every such rule is unenforced. Cross-file \$refs are
/// already inlined, so it needs no resolver.
const String payloadSchemaJson =
    '{"\$schema":"https://json-schema.org/draft/2020-12/schema","\$id":"https://trusttasks.org/spec/vta/attestation/status/0.1","title":"VTA Attestation — Status — payload","description":"Asks an agent which trusted execution environment it runs in. The payload carries nothing. The outer document members (id, type, issuer, recipient, issuedAt, expiresAt, proof) are owned by the framework — SPEC §6.3.","type":"object","additionalProperties":false,"properties":{"ext":{"\$ref":"#/\$defs/Ext","description":"Ecosystem-defined extension members per SPEC.md §4.5.1."}},"\$defs":{"Response":{"\$anchor":"response","title":"VTA Attestation Status — response payload","type":"object","additionalProperties":false,"required":["teeType","detected"],"properties":{"teeType":{"type":"string","enum":["nitro","sev-snp","simulated"],"description":"The platform whose evidence vta/attestation/report returns: nitro (AWS Nitro Enclaves), sev-snp (AMD SEV-SNP), or simulated (a development build whose evidence no verifier should accept)."},"detected":{"type":"boolean","description":"Whether the agent found the platform at boot. False means it was configured for one it did not find, and it produces no evidence."},"platformVersion":{"type":"string","minLength":1,"maxLength":256,"description":"The platform\'s own version string, when it reports one. Informational."},"ext":{"\$ref":"#/\$defs/Ext","description":"Ecosystem-defined extension members per SPEC.md §4.5.1."}}},"Ext":{"title":"Ext","description":"Vendor-namespaced extension object per SPEC.md §4.5.1. Each immediate key MUST be a reverse-DNS namespace; structure under each namespace is opaque to the framework.","type":"object","minProperties":1,"additionalProperties":true,"propertyNames":{"pattern":"^[a-z][a-z0-9-]*(\\\\.[a-z0-9-]+)+\$"}}}}';

/// As [payloadSchemaJson], for the success-response variant.
const String responsePayloadSchemaJson =
    '{"\$schema":"https://json-schema.org/draft/2020-12/schema","\$ref":"#/\$defs/Response","\$defs":{"Response":{"\$anchor":"response","title":"VTA Attestation Status — response payload","type":"object","additionalProperties":false,"required":["teeType","detected"],"properties":{"teeType":{"type":"string","enum":["nitro","sev-snp","simulated"],"description":"The platform whose evidence vta/attestation/report returns: nitro (AWS Nitro Enclaves), sev-snp (AMD SEV-SNP), or simulated (a development build whose evidence no verifier should accept)."},"detected":{"type":"boolean","description":"Whether the agent found the platform at boot. False means it was configured for one it did not find, and it produces no evidence."},"platformVersion":{"type":"string","minLength":1,"maxLength":256,"description":"The platform\'s own version string, when it reports one. Informational."},"ext":{"\$ref":"#/\$defs/Ext","description":"Ecosystem-defined extension members per SPEC.md §4.5.1."}}},"Ext":{"title":"Ext","description":"Vendor-namespaced extension object per SPEC.md §4.5.1. Each immediate key MUST be a reverse-DNS namespace; structure under each namespace is opaque to the framework.","type":"object","minProperties":1,"additionalProperties":true,"propertyNames":{"pattern":"^[a-z][a-z0-9-]*(\\\\.[a-z0-9-]+)+\$"}}}}';

/// The SPEC §7.2 policy for the request variant, taken from this
/// specification's front matter.
///
/// Pass it to [consumeInbound] — items 5b, 7 and 8 are per-specification and
/// cannot be derived from the document alone, and item 2 needs the schema it
/// carries.
const SpecPolicy spec = SpecPolicy(
  typeUri: typeUri,
  isBearer: false,
  isProofRequired: false,
  isRecipientRequired: true,
  isIssuedAtRequired: false,
  payloadSchema: payloadSchemaJson,
);

/// The SPEC §7.2 policy for the success-response variant.
///
/// `isRecipientRequired` tracks the *issuer* party's requirement, because a
/// response swaps the parties (§7.3 item 5).
const SpecPolicy responseSpec = SpecPolicy(
  typeUri: responseTypeUri,
  isBearer: false,
  isProofRequired: true,
  isRecipientRequired: true,
  isIssuedAtRequired: false,
  payloadSchema: responsePayloadSchemaJson,
);
