/**
 * Generated by scripts/build-ts-bindings.mjs — DO NOT EDIT BY HAND.
 * Source: specs/vta/attestation/config-report/0.1/payload.schema.json
 */

import type { Ext } from "../../../../_shared/components.js";


/**
 * Asks an agent for fresh attestation evidence committing to the configuration it booted, bound to a nonce the verifier chose. The outer document members (id, type, issuer, recipient, issuedAt, expiresAt, proof) are owned by the framework — SPEC §6.3.
 */
export interface VTAAttestationConfigReportPayload {
  /**
   * Thirty-two bytes the verifier generated for this request, lowercase hex. The agent binds exactly this into the evidence.
   */
  nonce: string;
  /**
   * Ecosystem-defined extension members per SPEC.md §4.5.1.
   */
  ext?: Ext;
}
export interface VTAAttestationConfigReportResponsePayload {
  /**
   * SHA-384 of the decoded configView bytes, base64 (standard). A convenience: the verifier recomputes it, and a mismatch with either the view or the evidence is a refusal.
   */
  configDigestSha384: string;
  /**
   * The canonical, secret-free view of the configuration the agent booted, base64 (standard): the exact bytes whose SHA-384 the evidence binds as its user data.
   */
  configView: string;
  /**
   * The request's nonce, echoed. A verifier checks the nonce inside the evidence, not this.
   */
  nonce: string;
  /**
   * The platform that produced the evidence. Informational and not covered by the evidence.
   */
  teeType: "nitro" | "sev-snp" | "simulated";
  /**
   * The platform's quote, base64 (a COSE_Sign1 attestation document for nitro).
   */
  evidence: string;
  /**
   * When the evidence was produced. Informational: freshness comes from the nonce.
   */
  generatedAt: string;
  /**
   * Ecosystem-defined extension members per SPEC.md §4.5.1.
   */
  ext?: Ext;
}

/** Shared definitions this specification references, re-exported under the names it used to declare them with. */
export type { Ext };

/** Trust Task type URI. */
export const TYPE_URI = "https://trusttasks.org/spec/vta/attestation/config-report/0.1" as const;

/** Stable alias for this specification's request payload shape. */
export type Payload = VTAAttestationConfigReportPayload;

/** Trust Task response type URI (request type URI + "#response"). */
export const RESPONSE_TYPE_URI = "https://trusttasks.org/spec/vta/attestation/config-report/0.1#response" as const;

/** Stable alias for this specification's success-response payload shape. */
export type Response = VTAAttestationConfigReportResponsePayload;

/**
 * This specification's payload schema, as a value.
 *
 * SPEC.md §7.2 item 2 is performed against this. It is shipped as data
 * rather than only as a `.json` file because TypeScript types are erased
 * at runtime: without a schema a consumer has nothing to validate, and
 * every REQUIRED payload member is optional in practice. Cross-file
 * `$ref`s are already inlined, so it needs no resolver.
 */
export const PAYLOAD_SCHEMA = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://trusttasks.org/spec/vta/attestation/config-report/0.1",
  "title": "VTA Attestation — Config Report — payload",
  "description": "Asks an agent for fresh attestation evidence committing to the configuration it booted, bound to a nonce the verifier chose. The outer document members (id, type, issuer, recipient, issuedAt, expiresAt, proof) are owned by the framework — SPEC §6.3.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "nonce"
  ],
  "properties": {
    "nonce": {
      "type": "string",
      "pattern": "^[0-9a-f]{64}$",
      "description": "Thirty-two bytes the verifier generated for this request, lowercase hex. The agent binds exactly this into the evidence."
    },
    "ext": {
      "$ref": "#/$defs/Ext",
      "description": "Ecosystem-defined extension members per SPEC.md §4.5.1."
    }
  },
  "$defs": {
    "Response": {
      "$anchor": "response",
      "title": "VTA Attestation Config Report — response payload",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "configDigestSha384",
        "configView",
        "nonce",
        "teeType",
        "evidence",
        "generatedAt"
      ],
      "properties": {
        "configDigestSha384": {
          "type": "string",
          "pattern": "^[A-Za-z0-9+/]{64}$",
          "description": "SHA-384 of the decoded configView bytes, base64 (standard). A convenience: the verifier recomputes it, and a mismatch with either the view or the evidence is a refusal."
        },
        "configView": {
          "type": "string",
          "minLength": 1,
          "maxLength": 65536,
          "pattern": "^[A-Za-z0-9+/]+={0,2}$",
          "description": "The canonical, secret-free view of the configuration the agent booted, base64 (standard): the exact bytes whose SHA-384 the evidence binds as its user data."
        },
        "nonce": {
          "type": "string",
          "pattern": "^[0-9a-f]{64}$",
          "description": "The request's nonce, echoed. A verifier checks the nonce inside the evidence, not this."
        },
        "teeType": {
          "type": "string",
          "enum": [
            "nitro",
            "sev-snp",
            "simulated"
          ],
          "description": "The platform that produced the evidence. Informational and not covered by the evidence."
        },
        "evidence": {
          "type": "string",
          "minLength": 1,
          "maxLength": 65536,
          "pattern": "^[A-Za-z0-9+/_-]+={0,2}$",
          "description": "The platform's quote, base64 (a COSE_Sign1 attestation document for nitro)."
        },
        "generatedAt": {
          "type": "string",
          "format": "date-time",
          "description": "When the evidence was produced. Informational: freshness comes from the nonce."
        },
        "ext": {
          "$ref": "#/$defs/Ext",
          "description": "Ecosystem-defined extension members per SPEC.md §4.5.1."
        }
      }
    },
    "Ext": {
      "title": "Ext",
      "description": "Vendor-namespaced extension object per SPEC.md §4.5.1. Each immediate key MUST be a reverse-DNS namespace; structure under each namespace is opaque to the framework.",
      "type": "object",
      "minProperties": 1,
      "additionalProperties": true,
      "propertyNames": {
        "pattern": "^[a-z][a-z0-9-]*(\\.[a-z0-9-]+)+$"
      }
    }
  }
} as const;

/** As {@link PAYLOAD_SCHEMA}, for the success-response variant. */
export const RESPONSE_PAYLOAD_SCHEMA = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$ref": "#/$defs/Response",
  "$defs": {
    "Response": {
      "$anchor": "response",
      "title": "VTA Attestation Config Report — response payload",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "configDigestSha384",
        "configView",
        "nonce",
        "teeType",
        "evidence",
        "generatedAt"
      ],
      "properties": {
        "configDigestSha384": {
          "type": "string",
          "pattern": "^[A-Za-z0-9+/]{64}$",
          "description": "SHA-384 of the decoded configView bytes, base64 (standard). A convenience: the verifier recomputes it, and a mismatch with either the view or the evidence is a refusal."
        },
        "configView": {
          "type": "string",
          "minLength": 1,
          "maxLength": 65536,
          "pattern": "^[A-Za-z0-9+/]+={0,2}$",
          "description": "The canonical, secret-free view of the configuration the agent booted, base64 (standard): the exact bytes whose SHA-384 the evidence binds as its user data."
        },
        "nonce": {
          "type": "string",
          "pattern": "^[0-9a-f]{64}$",
          "description": "The request's nonce, echoed. A verifier checks the nonce inside the evidence, not this."
        },
        "teeType": {
          "type": "string",
          "enum": [
            "nitro",
            "sev-snp",
            "simulated"
          ],
          "description": "The platform that produced the evidence. Informational and not covered by the evidence."
        },
        "evidence": {
          "type": "string",
          "minLength": 1,
          "maxLength": 65536,
          "pattern": "^[A-Za-z0-9+/_-]+={0,2}$",
          "description": "The platform's quote, base64 (a COSE_Sign1 attestation document for nitro)."
        },
        "generatedAt": {
          "type": "string",
          "format": "date-time",
          "description": "When the evidence was produced. Informational: freshness comes from the nonce."
        },
        "ext": {
          "$ref": "#/$defs/Ext",
          "description": "Ecosystem-defined extension members per SPEC.md §4.5.1."
        }
      }
    },
    "Ext": {
      "title": "Ext",
      "description": "Vendor-namespaced extension object per SPEC.md §4.5.1. Each immediate key MUST be a reverse-DNS namespace; structure under each namespace is opaque to the framework.",
      "type": "object",
      "minProperties": 1,
      "additionalProperties": true,
      "propertyNames": {
        "pattern": "^[a-z][a-z0-9-]*(\\.[a-z0-9-]+)+$"
      }
    }
  }
} as const;

/**
 * SPEC.md §7.2 policy for the request variant, from this specification's
 * front matter. Pass to `consumeInbound` — items 5b, 7 and 8 are
 * per-specification and cannot be derived from the document alone, and
 * item 2 needs the schema this carries.
 */
export const SPEC = {
  typeUri: TYPE_URI,
  isBearer: false,
  isProofRequired: false,
  isRecipientRequired: true,
  isIssuedAtRequired: false,
  payloadSchema: PAYLOAD_SCHEMA,
} as const;

/**
 * SPEC.md §7.2 policy for the success-response variant. `isRecipientRequired`
 * tracks the *issuer* party's requirement because a response swaps the
 * parties (§7.3 item 5).
 */
export const RESPONSE_SPEC = {
  typeUri: RESPONSE_TYPE_URI,
  isBearer: false,
  isProofRequired: true,
  isRecipientRequired: true,
  isIssuedAtRequired: false,
  payloadSchema: RESPONSE_PAYLOAD_SCHEMA,
} as const;
