/**
 * Generated by scripts/build-ts-bindings.mjs — DO NOT EDIT BY HAND.
 * Source: specs/git-ns/repo/list/0.1/payload.schema.json
 */

import type { Bootstrap, Did_GitNsV0_3 as Did, Ext, ForgeId, NamespaceId, RepoResource, RepoVisibility } from "../../../../_shared/components.js";


/**
 * A level of the bridge's forge-neutral role ladder, lowest first: the vocabulary role drift's `observed` and `expected` are reported in. `none` is no direct role on the repository.
 */
export type MappedRole = "none" | "read" | "triage" | "write" | "maintain" | "admin";

/**
 * An administrator lists the repositories recorded in the namespaces they administer — every one, for a holder of the community-administrator capability — with owners, right counts, bootstrap, sync and forge status.
 */
export interface GitNamespacesListRepositoriesPayload {
  /**
   * Only the repositories in this namespace. It must be one the caller administers; a namespace they do not administer, or one this VTC does not have, is refused with `notAdministrator` alike.
   */
  namespace?: NamespaceId;
  ext?: Ext;
}
/**
 * The repositories in the namespaces the caller administers, or in the one asked for.
 */
export interface GitNamespacesListRepositoriesResponsePayload {
  /**
   * Every repository recorded in an administered namespace, in any state, ordered by `resource`; for a holder of the community-administrator capability without `namespace`, also every repository whose namespace is no longer bound.
   */
  repos: RepoStatus[];
  ext?: Ext;
}
/**
 * One repository as its administrators govern it: who owns it, how many hold rights on it, how far commit trust is set up, and how its forge compares with the VTC's projection.
 */
export interface RepoStatus {
  /**
   * The VTC's identifier for the repository record.
   */
  id: string;
  /**
   * The namespace it was recorded in. For a `detached` repository, possibly one no longer bound.
   */
  namespace: NamespaceId;
  resource: RepoResource;
  /**
   * The forge's repository id, once confirmed.
   */
  forgeId?: ForgeId;
  visibility: RepoVisibility;
  /**
   * As `RepoSummary.state` in the shared schema.
   */
  state: "pendingCreate" | "active" | "archived" | "detached" | "orphaned" | "unmanaged";
  /**
   * The DIDs holding a live, explicitly recorded `git.repo.own` on it.
   */
  owners: Did[];
  /**
   * How many live records of `git.repo.maintain` it has. Implied rights are not counted.
   */
  maintainers: number;
  /**
   * How many live records of `git.commit.sign` it has. Implied rights are not counted.
   */
  committers: number;
  bootstrap: Bootstrap;
  /**
   * As `Sync.state` in the shared schema.
   */
  syncState: "inSync" | "drift" | "pending" | "unchecked";
  /**
   * When the forge was last compared. Absent if never.
   */
  checkedAt?: string;
  /**
   * How many drift items are outstanding. The items themselves are in `git-ns/view`.
   */
  driftCount: number;
  /**
   * The step that failed on the last create or bootstrap.
   */
  failedStep?: string;
  /**
   * What the bridge said when that step failed.
   */
  lastError?: string;
  /**
   * Who created it through the VTC. Absent for an adopted or unmanaged repository.
   */
  createdBy?: Did;
  /**
   * When the VTC first recorded it.
   */
  createdAt: string;
  /**
   * The guard in force against a pull request satisfying its own check, as the bridge last reported it: `requiredWorkflow`, `codeOwnerReview`, `bridgePostedCheck`, `protectedFiles` or `none`. A client treats any other value as `none`.
   */
  guard?: string;
  /**
   * Per-step outcomes of the last create, bootstrap or inspect job. Empty until one has been reported.
   *
   * @maxItems 64
   */
  steps: StepOutcome[];
  lastCheck?: LastCheck;
  roleMap?: RoleMap;
  /**
   * The bridge last projected this repository's roles under an earlier role map, and the re-projection queued for it has not yet succeeded.
   */
  roleMapStale: boolean;
}
/**
 * One step of the last create, bootstrap or inspect job on the repository, as the bridge reported it.
 */
export interface StepOutcome {
  /**
   * The step, in the bridge's words (`workflow`, `keyring`, `variables`, `requiredCheck`).
   */
  step: string;
  /**
   * `applied`, `unchanged`, `failed` or `skipped`. A client shows any other value as reported.
   */
  outcome: string;
  /**
   * What the bridge said about it — an error, or why it was skipped.
   */
  detail?: string;
}
/**
 * The last verify-trust check run the bridge saw on the repository.
 */
export interface LastCheck {
  /**
   * The check's conclusion, in the forge's words (`success`, `failure`).
   */
  conclusion: string;
  /**
   * When the check concluded.
   */
  at: string;
  /**
   * The commit it ran on.
   */
  sha?: string;
}
/**
 * The forge role each right projects to on this repository under the serving bridge's reported map. Absent while the namespace's map is unknown.
 */
export interface RoleMap {
  own: MappedRole;
  maintain: MappedRole;
  commit: MappedRole;
}

/** Shared definitions this specification references, re-exported under the names it used to declare them with. */
export type { Bootstrap, Did, Ext, ForgeId, NamespaceId, RepoResource, RepoVisibility };

/** Trust Task type URI. */
export const TYPE_URI = "https://trusttasks.org/spec/git-ns/repo/list/0.1" as const;

/** Stable alias for this specification's request payload shape. */
export type Payload = GitNamespacesListRepositoriesPayload;

/** Trust Task response type URI (request type URI + "#response"). */
export const RESPONSE_TYPE_URI = "https://trusttasks.org/spec/git-ns/repo/list/0.1#response" as const;

/** Stable alias for this specification's success-response payload shape. */
export type Response = GitNamespacesListRepositoriesResponsePayload;

/**
 * This specification's payload schema, as a value.
 *
 * SPEC.md §7.2 item 2 is performed against this. It is shipped as data
 * rather than only as a `.json` file because TypeScript types are erased
 * at runtime: without a schema a consumer has nothing to validate, and
 * every REQUIRED payload member is optional in practice. Cross-file
 * `$ref`s are already inlined, so it needs no resolver.
 */
export const PAYLOAD_SCHEMA = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://trusttasks.org/spec/git-ns/repo/list/0.1",
  "title": "Git Namespaces — List Repositories — payload",
  "description": "An administrator lists the repositories recorded in the namespaces they administer — every one, for a holder of the community-administrator capability — with owners, right counts, bootstrap, sync and forge status.",
  "type": "object",
  "additionalProperties": false,
  "required": [],
  "properties": {
    "namespace": {
      "$ref": "#/$defs/NamespaceId",
      "description": "Only the repositories in this namespace. It must be one the caller administers; a namespace they do not administer, or one this VTC does not have, is refused with `notAdministrator` alike."
    },
    "ext": {
      "$ref": "#/$defs/Ext"
    }
  },
  "$defs": {
    "MappedRole": {
      "title": "MappedRole",
      "type": "string",
      "enum": [
        "none",
        "read",
        "triage",
        "write",
        "maintain",
        "admin"
      ],
      "description": "A level of the bridge's forge-neutral role ladder, lowest first: the vocabulary role drift's `observed` and `expected` are reported in. `none` is no direct role on the repository."
    },
    "RoleMap": {
      "title": "RoleMap",
      "description": "The forge role each repository right is given, as the forge applies it: after the forge's own ladder has rounded it down. `own` is the role `git.repo.own` projects to, `maintain` that of `git.repo.maintain`, `commit` that of `git.commit.sign` (`none` is fork-based contribution). There is no member for `git.ns.admin` or `git.repo.create`, which project to no forge role whatever a bridge is configured with. Ordered: `own` is at least `maintain`, which is at least `commit`, and `commit` is at most `write`.",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "own",
        "maintain",
        "commit"
      ],
      "properties": {
        "own": {
          "$ref": "#/$defs/MappedRole"
        },
        "maintain": {
          "$ref": "#/$defs/MappedRole"
        },
        "commit": {
          "$ref": "#/$defs/MappedRole"
        }
      }
    },
    "StepOutcome": {
      "title": "StepOutcome",
      "description": "One step of the last create, bootstrap or inspect job on the repository, as the bridge reported it.",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "step",
        "outcome"
      ],
      "properties": {
        "step": {
          "type": "string",
          "minLength": 1,
          "maxLength": 64,
          "description": "The step, in the bridge's words (`workflow`, `keyring`, `variables`, `requiredCheck`)."
        },
        "outcome": {
          "type": "string",
          "minLength": 1,
          "maxLength": 32,
          "description": "`applied`, `unchanged`, `failed` or `skipped`. A client shows any other value as reported."
        },
        "detail": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4096,
          "description": "What the bridge said about it — an error, or why it was skipped."
        }
      }
    },
    "LastCheck": {
      "title": "LastCheck",
      "description": "The last verify-trust check run the bridge saw on the repository.",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "conclusion",
        "at"
      ],
      "properties": {
        "conclusion": {
          "type": "string",
          "minLength": 1,
          "maxLength": 64,
          "description": "The check's conclusion, in the forge's words (`success`, `failure`)."
        },
        "at": {
          "type": "string",
          "format": "date-time",
          "description": "When the check concluded."
        },
        "sha": {
          "type": "string",
          "minLength": 1,
          "maxLength": 64,
          "description": "The commit it ran on."
        }
      }
    },
    "RepoStatus": {
      "title": "RepoStatus",
      "description": "One repository as its administrators govern it: who owns it, how many hold rights on it, how far commit trust is set up, and how its forge compares with the VTC's projection.",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "namespace",
        "resource",
        "visibility",
        "state",
        "owners",
        "maintainers",
        "committers",
        "bootstrap",
        "syncState",
        "driftCount",
        "createdAt",
        "steps",
        "roleMapStale"
      ],
      "properties": {
        "id": {
          "type": "string",
          "minLength": 1,
          "maxLength": 128,
          "description": "The VTC's identifier for the repository record."
        },
        "namespace": {
          "$ref": "#/$defs/NamespaceId",
          "description": "The namespace it was recorded in. For a `detached` repository, possibly one no longer bound."
        },
        "resource": {
          "$ref": "#/$defs/RepoResource"
        },
        "forgeId": {
          "$ref": "#/$defs/ForgeId",
          "description": "The forge's repository id, once confirmed."
        },
        "visibility": {
          "$ref": "#/$defs/RepoVisibility"
        },
        "state": {
          "type": "string",
          "enum": [
            "pendingCreate",
            "active",
            "archived",
            "detached",
            "orphaned",
            "unmanaged"
          ],
          "description": "As `RepoSummary.state` in the shared schema."
        },
        "owners": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/Did"
          },
          "description": "The DIDs holding a live, explicitly recorded `git.repo.own` on it."
        },
        "maintainers": {
          "type": "integer",
          "minimum": 0,
          "description": "How many live records of `git.repo.maintain` it has. Implied rights are not counted."
        },
        "committers": {
          "type": "integer",
          "minimum": 0,
          "description": "How many live records of `git.commit.sign` it has. Implied rights are not counted."
        },
        "bootstrap": {
          "$ref": "#/$defs/Bootstrap"
        },
        "syncState": {
          "type": "string",
          "enum": [
            "inSync",
            "drift",
            "pending",
            "unchecked"
          ],
          "description": "As `Sync.state` in the shared schema."
        },
        "checkedAt": {
          "type": "string",
          "format": "date-time",
          "description": "When the forge was last compared. Absent if never."
        },
        "driftCount": {
          "type": "integer",
          "minimum": 0,
          "description": "How many drift items are outstanding. The items themselves are in `git-ns/view`."
        },
        "failedStep": {
          "type": "string",
          "minLength": 1,
          "maxLength": 64,
          "description": "The step that failed on the last create or bootstrap."
        },
        "lastError": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4096,
          "description": "What the bridge said when that step failed."
        },
        "createdBy": {
          "$ref": "#/$defs/Did",
          "description": "Who created it through the VTC. Absent for an adopted or unmanaged repository."
        },
        "createdAt": {
          "type": "string",
          "format": "date-time",
          "description": "When the VTC first recorded it."
        },
        "guard": {
          "type": "string",
          "minLength": 1,
          "maxLength": 64,
          "description": "The guard in force against a pull request satisfying its own check, as the bridge last reported it: `requiredWorkflow`, `codeOwnerReview`, `bridgePostedCheck`, `protectedFiles` or `none`. A client treats any other value as `none`."
        },
        "steps": {
          "type": "array",
          "maxItems": 64,
          "items": {
            "$ref": "#/$defs/StepOutcome"
          },
          "description": "Per-step outcomes of the last create, bootstrap or inspect job. Empty until one has been reported."
        },
        "lastCheck": {
          "$ref": "#/$defs/LastCheck"
        },
        "roleMap": {
          "$ref": "#/$defs/RoleMap",
          "description": "The forge role each right projects to on this repository under the serving bridge's reported map. Absent while the namespace's map is unknown."
        },
        "roleMapStale": {
          "type": "boolean",
          "description": "The bridge last projected this repository's roles under an earlier role map, and the re-projection queued for it has not yet succeeded."
        }
      }
    },
    "Response": {
      "$anchor": "response",
      "title": "Git Namespaces — List Repositories — response payload",
      "description": "The repositories in the namespaces the caller administers, or in the one asked for.",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "repos"
      ],
      "properties": {
        "repos": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/RepoStatus"
          },
          "description": "Every repository recorded in an administered namespace, in any state, ordered by `resource`; for a holder of the community-administrator capability without `namespace`, also every repository whose namespace is no longer bound."
        },
        "ext": {
          "$ref": "#/$defs/Ext"
        }
      }
    },
    "Ext": {
      "title": "Ext",
      "description": "Vendor-namespaced extension object per SPEC.md §4.5.1. Each immediate key MUST be a reverse-DNS namespace; structure under each namespace is opaque to the framework.",
      "type": "object",
      "minProperties": 1,
      "additionalProperties": true,
      "propertyNames": {
        "pattern": "^[a-z][a-z0-9-]*(\\.[a-z0-9-]+)+$"
      }
    },
    "Did": {
      "title": "Did",
      "description": "A bare DID in the W3C DID Core syntax (§3.1): `did:`, a method name of lowercase letters and digits, `:`, and a method-specific id of colon-separated segments drawn from `A-Z a-z 0-9 . - _` and percent-encoded octets, the last segment non-empty. A DID URL is not a DID: no path, query or fragment (`/`, `?`, `#`), so a verification-method id such as `did:key:z6Mk…#z6Mk…` is refused. Compared by exact string equality — no case folding or percent-decoding. A consumer MUST still treat the value as data: the pattern keeps shell metacharacters, whitespace and quotes out of the wire form, but it does not make a DID safe to splice into a command or markup.",
      "type": "string",
      "maxLength": 2048,
      "pattern": "^did:[a-z0-9]+:(?:(?:[A-Za-z0-9._-]|%[0-9A-Fa-f]{2})*:)*(?:[A-Za-z0-9._-]|%[0-9A-Fa-f]{2})+$"
    },
    "Bootstrap": {
      "title": "Bootstrap",
      "description": "Whether each step that turns commit trust on for a repository is in place, as last reported. A step that this forge's plan does not need reads `true`.",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "workflow",
        "keyring",
        "variables",
        "requiredCheck"
      ],
      "properties": {
        "workflow": {
          "type": "boolean",
          "description": "The verify-trust check runs on the repository's pull requests — from a workflow committed to it, or, where the forge supports it, required on it from the namespace's own bridge-managed workflow repository at a pinned commit."
        },
        "keyring": {
          "type": "boolean",
          "description": "The exempt platform keyring for forge-signed merge commits is committed, or the forge's plan does not need one."
        },
        "variables": {
          "type": "boolean",
          "description": "The repository names the Trust Registry and this VTC as its trust anchors."
        },
        "requiredCheck": {
          "type": "boolean",
          "description": "The forge refuses to merge into the default branch unless the verify-trust check passes, with no bypass, and a pull request cannot change what that check runs: an organisation-required workflow, code-owner review of workflow files, or protected workflow paths, as the forge allows."
        }
      }
    },
    "RepoVisibility": {
      "title": "RepoVisibility",
      "type": "string",
      "enum": [
        "public",
        "private"
      ],
      "description": "Repository visibility on the forge."
    },
    "ForgeId": {
      "title": "ForgeId",
      "description": "An identifier the forge itself assigns — a repository id, a user or organisation id — carried as a string so a forge whose ids are not numbers needs no new version. GitHub and Forgejo ids are decimal integers written as strings (`\"812736451\"`). Unlike a name, it survives renames and transfers, which is why rights and bindings are keyed by it.",
      "type": "string",
      "minLength": 1,
      "maxLength": 64
    },
    "RepoResource": {
      "title": "RepoResource",
      "description": "A forge-qualified resource naming exactly one repository: `<forge-host>/<owner>/<repo>`, lowercase.",
      "type": "string",
      "maxLength": 455,
      "pattern": "^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?(?:\\.[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)+/[a-z0-9_-][a-z0-9._-]{0,99}/[a-z0-9_-][a-z0-9._-]{0,99}$"
    },
    "NamespaceId": {
      "title": "NamespaceId",
      "description": "The VTC's opaque identifier for a namespace, assigned when it is bound. Stable for the life of the binding; never reused for another binding.",
      "type": "string",
      "minLength": 1,
      "maxLength": 128
    }
  }
} as const;

/** As {@link PAYLOAD_SCHEMA}, for the success-response variant. */
export const RESPONSE_PAYLOAD_SCHEMA = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$ref": "#/$defs/Response",
  "$defs": {
    "MappedRole": {
      "title": "MappedRole",
      "type": "string",
      "enum": [
        "none",
        "read",
        "triage",
        "write",
        "maintain",
        "admin"
      ],
      "description": "A level of the bridge's forge-neutral role ladder, lowest first: the vocabulary role drift's `observed` and `expected` are reported in. `none` is no direct role on the repository."
    },
    "RoleMap": {
      "title": "RoleMap",
      "description": "The forge role each repository right is given, as the forge applies it: after the forge's own ladder has rounded it down. `own` is the role `git.repo.own` projects to, `maintain` that of `git.repo.maintain`, `commit` that of `git.commit.sign` (`none` is fork-based contribution). There is no member for `git.ns.admin` or `git.repo.create`, which project to no forge role whatever a bridge is configured with. Ordered: `own` is at least `maintain`, which is at least `commit`, and `commit` is at most `write`.",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "own",
        "maintain",
        "commit"
      ],
      "properties": {
        "own": {
          "$ref": "#/$defs/MappedRole"
        },
        "maintain": {
          "$ref": "#/$defs/MappedRole"
        },
        "commit": {
          "$ref": "#/$defs/MappedRole"
        }
      }
    },
    "StepOutcome": {
      "title": "StepOutcome",
      "description": "One step of the last create, bootstrap or inspect job on the repository, as the bridge reported it.",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "step",
        "outcome"
      ],
      "properties": {
        "step": {
          "type": "string",
          "minLength": 1,
          "maxLength": 64,
          "description": "The step, in the bridge's words (`workflow`, `keyring`, `variables`, `requiredCheck`)."
        },
        "outcome": {
          "type": "string",
          "minLength": 1,
          "maxLength": 32,
          "description": "`applied`, `unchanged`, `failed` or `skipped`. A client shows any other value as reported."
        },
        "detail": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4096,
          "description": "What the bridge said about it — an error, or why it was skipped."
        }
      }
    },
    "LastCheck": {
      "title": "LastCheck",
      "description": "The last verify-trust check run the bridge saw on the repository.",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "conclusion",
        "at"
      ],
      "properties": {
        "conclusion": {
          "type": "string",
          "minLength": 1,
          "maxLength": 64,
          "description": "The check's conclusion, in the forge's words (`success`, `failure`)."
        },
        "at": {
          "type": "string",
          "format": "date-time",
          "description": "When the check concluded."
        },
        "sha": {
          "type": "string",
          "minLength": 1,
          "maxLength": 64,
          "description": "The commit it ran on."
        }
      }
    },
    "RepoStatus": {
      "title": "RepoStatus",
      "description": "One repository as its administrators govern it: who owns it, how many hold rights on it, how far commit trust is set up, and how its forge compares with the VTC's projection.",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "namespace",
        "resource",
        "visibility",
        "state",
        "owners",
        "maintainers",
        "committers",
        "bootstrap",
        "syncState",
        "driftCount",
        "createdAt",
        "steps",
        "roleMapStale"
      ],
      "properties": {
        "id": {
          "type": "string",
          "minLength": 1,
          "maxLength": 128,
          "description": "The VTC's identifier for the repository record."
        },
        "namespace": {
          "$ref": "#/$defs/NamespaceId",
          "description": "The namespace it was recorded in. For a `detached` repository, possibly one no longer bound."
        },
        "resource": {
          "$ref": "#/$defs/RepoResource"
        },
        "forgeId": {
          "$ref": "#/$defs/ForgeId",
          "description": "The forge's repository id, once confirmed."
        },
        "visibility": {
          "$ref": "#/$defs/RepoVisibility"
        },
        "state": {
          "type": "string",
          "enum": [
            "pendingCreate",
            "active",
            "archived",
            "detached",
            "orphaned",
            "unmanaged"
          ],
          "description": "As `RepoSummary.state` in the shared schema."
        },
        "owners": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/Did"
          },
          "description": "The DIDs holding a live, explicitly recorded `git.repo.own` on it."
        },
        "maintainers": {
          "type": "integer",
          "minimum": 0,
          "description": "How many live records of `git.repo.maintain` it has. Implied rights are not counted."
        },
        "committers": {
          "type": "integer",
          "minimum": 0,
          "description": "How many live records of `git.commit.sign` it has. Implied rights are not counted."
        },
        "bootstrap": {
          "$ref": "#/$defs/Bootstrap"
        },
        "syncState": {
          "type": "string",
          "enum": [
            "inSync",
            "drift",
            "pending",
            "unchecked"
          ],
          "description": "As `Sync.state` in the shared schema."
        },
        "checkedAt": {
          "type": "string",
          "format": "date-time",
          "description": "When the forge was last compared. Absent if never."
        },
        "driftCount": {
          "type": "integer",
          "minimum": 0,
          "description": "How many drift items are outstanding. The items themselves are in `git-ns/view`."
        },
        "failedStep": {
          "type": "string",
          "minLength": 1,
          "maxLength": 64,
          "description": "The step that failed on the last create or bootstrap."
        },
        "lastError": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4096,
          "description": "What the bridge said when that step failed."
        },
        "createdBy": {
          "$ref": "#/$defs/Did",
          "description": "Who created it through the VTC. Absent for an adopted or unmanaged repository."
        },
        "createdAt": {
          "type": "string",
          "format": "date-time",
          "description": "When the VTC first recorded it."
        },
        "guard": {
          "type": "string",
          "minLength": 1,
          "maxLength": 64,
          "description": "The guard in force against a pull request satisfying its own check, as the bridge last reported it: `requiredWorkflow`, `codeOwnerReview`, `bridgePostedCheck`, `protectedFiles` or `none`. A client treats any other value as `none`."
        },
        "steps": {
          "type": "array",
          "maxItems": 64,
          "items": {
            "$ref": "#/$defs/StepOutcome"
          },
          "description": "Per-step outcomes of the last create, bootstrap or inspect job. Empty until one has been reported."
        },
        "lastCheck": {
          "$ref": "#/$defs/LastCheck"
        },
        "roleMap": {
          "$ref": "#/$defs/RoleMap",
          "description": "The forge role each right projects to on this repository under the serving bridge's reported map. Absent while the namespace's map is unknown."
        },
        "roleMapStale": {
          "type": "boolean",
          "description": "The bridge last projected this repository's roles under an earlier role map, and the re-projection queued for it has not yet succeeded."
        }
      }
    },
    "Response": {
      "$anchor": "response",
      "title": "Git Namespaces — List Repositories — response payload",
      "description": "The repositories in the namespaces the caller administers, or in the one asked for.",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "repos"
      ],
      "properties": {
        "repos": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/RepoStatus"
          },
          "description": "Every repository recorded in an administered namespace, in any state, ordered by `resource`; for a holder of the community-administrator capability without `namespace`, also every repository whose namespace is no longer bound."
        },
        "ext": {
          "$ref": "#/$defs/Ext"
        }
      }
    },
    "Ext": {
      "title": "Ext",
      "description": "Vendor-namespaced extension object per SPEC.md §4.5.1. Each immediate key MUST be a reverse-DNS namespace; structure under each namespace is opaque to the framework.",
      "type": "object",
      "minProperties": 1,
      "additionalProperties": true,
      "propertyNames": {
        "pattern": "^[a-z][a-z0-9-]*(\\.[a-z0-9-]+)+$"
      }
    },
    "Did": {
      "title": "Did",
      "description": "A bare DID in the W3C DID Core syntax (§3.1): `did:`, a method name of lowercase letters and digits, `:`, and a method-specific id of colon-separated segments drawn from `A-Z a-z 0-9 . - _` and percent-encoded octets, the last segment non-empty. A DID URL is not a DID: no path, query or fragment (`/`, `?`, `#`), so a verification-method id such as `did:key:z6Mk…#z6Mk…` is refused. Compared by exact string equality — no case folding or percent-decoding. A consumer MUST still treat the value as data: the pattern keeps shell metacharacters, whitespace and quotes out of the wire form, but it does not make a DID safe to splice into a command or markup.",
      "type": "string",
      "maxLength": 2048,
      "pattern": "^did:[a-z0-9]+:(?:(?:[A-Za-z0-9._-]|%[0-9A-Fa-f]{2})*:)*(?:[A-Za-z0-9._-]|%[0-9A-Fa-f]{2})+$"
    },
    "Bootstrap": {
      "title": "Bootstrap",
      "description": "Whether each step that turns commit trust on for a repository is in place, as last reported. A step that this forge's plan does not need reads `true`.",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "workflow",
        "keyring",
        "variables",
        "requiredCheck"
      ],
      "properties": {
        "workflow": {
          "type": "boolean",
          "description": "The verify-trust check runs on the repository's pull requests — from a workflow committed to it, or, where the forge supports it, required on it from the namespace's own bridge-managed workflow repository at a pinned commit."
        },
        "keyring": {
          "type": "boolean",
          "description": "The exempt platform keyring for forge-signed merge commits is committed, or the forge's plan does not need one."
        },
        "variables": {
          "type": "boolean",
          "description": "The repository names the Trust Registry and this VTC as its trust anchors."
        },
        "requiredCheck": {
          "type": "boolean",
          "description": "The forge refuses to merge into the default branch unless the verify-trust check passes, with no bypass, and a pull request cannot change what that check runs: an organisation-required workflow, code-owner review of workflow files, or protected workflow paths, as the forge allows."
        }
      }
    },
    "RepoVisibility": {
      "title": "RepoVisibility",
      "type": "string",
      "enum": [
        "public",
        "private"
      ],
      "description": "Repository visibility on the forge."
    },
    "ForgeId": {
      "title": "ForgeId",
      "description": "An identifier the forge itself assigns — a repository id, a user or organisation id — carried as a string so a forge whose ids are not numbers needs no new version. GitHub and Forgejo ids are decimal integers written as strings (`\"812736451\"`). Unlike a name, it survives renames and transfers, which is why rights and bindings are keyed by it.",
      "type": "string",
      "minLength": 1,
      "maxLength": 64
    },
    "RepoResource": {
      "title": "RepoResource",
      "description": "A forge-qualified resource naming exactly one repository: `<forge-host>/<owner>/<repo>`, lowercase.",
      "type": "string",
      "maxLength": 455,
      "pattern": "^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?(?:\\.[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)+/[a-z0-9_-][a-z0-9._-]{0,99}/[a-z0-9_-][a-z0-9._-]{0,99}$"
    },
    "NamespaceId": {
      "title": "NamespaceId",
      "description": "The VTC's opaque identifier for a namespace, assigned when it is bound. Stable for the life of the binding; never reused for another binding.",
      "type": "string",
      "minLength": 1,
      "maxLength": 128
    }
  }
} as const;

/**
 * SPEC.md §7.2 policy for the request variant, from this specification's
 * front matter. Pass to `consumeInbound` — items 5b, 7 and 8 are
 * per-specification and cannot be derived from the document alone, and
 * item 2 needs the schema this carries.
 */
export const SPEC = {
  typeUri: TYPE_URI,
  isBearer: false,
  isProofRequired: true,
  isRecipientRequired: true,
  isIssuedAtRequired: false,
  payloadSchema: PAYLOAD_SCHEMA,
} as const;

/**
 * SPEC.md §7.2 policy for the success-response variant. `isRecipientRequired`
 * tracks the *issuer* party's requirement because a response swaps the
 * parties (§7.3 item 5).
 */
export const RESPONSE_SPEC = {
  typeUri: RESPONSE_TYPE_URI,
  isBearer: false,
  isProofRequired: true,
  isRecipientRequired: true,
  isIssuedAtRequired: false,
  payloadSchema: RESPONSE_PAYLOAD_SCHEMA,
} as const;
