/**
 * Generated by scripts/build-ts-bindings.mjs — DO NOT EDIT BY HAND.
 * Source: specs/vta/attestation/status/0.1/payload.schema.json
 */

import type { Ext } from "../../../../_shared/components.js";


/**
 * Asks an agent which trusted execution environment it runs in. The payload carries nothing. The outer document members (id, type, issuer, recipient, issuedAt, expiresAt, proof) are owned by the framework — SPEC §6.3.
 */
export interface VTAAttestationStatusPayload {
  /**
   * Ecosystem-defined extension members per SPEC.md §4.5.1.
   */
  ext?: Ext;
}
export interface VTAAttestationStatusResponsePayload {
  /**
   * The platform whose evidence vta/attestation/report returns: nitro (AWS Nitro Enclaves), sev-snp (AMD SEV-SNP), or simulated (a development build whose evidence no verifier should accept).
   */
  teeType: "nitro" | "sev-snp" | "simulated";
  /**
   * Whether the agent found the platform at boot. False means it was configured for one it did not find, and it produces no evidence.
   */
  detected: boolean;
  /**
   * The platform's own version string, when it reports one. Informational.
   */
  platformVersion?: string;
  /**
   * Ecosystem-defined extension members per SPEC.md §4.5.1.
   */
  ext?: Ext;
}

/** Shared definitions this specification references, re-exported under the names it used to declare them with. */
export type { Ext };

/** Trust Task type URI. */
export const TYPE_URI = "https://trusttasks.org/spec/vta/attestation/status/0.1" as const;

/** Stable alias for this specification's request payload shape. */
export type Payload = VTAAttestationStatusPayload;

/** Trust Task response type URI (request type URI + "#response"). */
export const RESPONSE_TYPE_URI = "https://trusttasks.org/spec/vta/attestation/status/0.1#response" as const;

/** Stable alias for this specification's success-response payload shape. */
export type Response = VTAAttestationStatusResponsePayload;

/**
 * This specification's payload schema, as a value.
 *
 * SPEC.md §7.2 item 2 is performed against this. It is shipped as data
 * rather than only as a `.json` file because TypeScript types are erased
 * at runtime: without a schema a consumer has nothing to validate, and
 * every REQUIRED payload member is optional in practice. Cross-file
 * `$ref`s are already inlined, so it needs no resolver.
 */
export const PAYLOAD_SCHEMA = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://trusttasks.org/spec/vta/attestation/status/0.1",
  "title": "VTA Attestation — Status — payload",
  "description": "Asks an agent which trusted execution environment it runs in. The payload carries nothing. The outer document members (id, type, issuer, recipient, issuedAt, expiresAt, proof) are owned by the framework — SPEC §6.3.",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "ext": {
      "$ref": "#/$defs/Ext",
      "description": "Ecosystem-defined extension members per SPEC.md §4.5.1."
    }
  },
  "$defs": {
    "Response": {
      "$anchor": "response",
      "title": "VTA Attestation Status — response payload",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "teeType",
        "detected"
      ],
      "properties": {
        "teeType": {
          "type": "string",
          "enum": [
            "nitro",
            "sev-snp",
            "simulated"
          ],
          "description": "The platform whose evidence vta/attestation/report returns: nitro (AWS Nitro Enclaves), sev-snp (AMD SEV-SNP), or simulated (a development build whose evidence no verifier should accept)."
        },
        "detected": {
          "type": "boolean",
          "description": "Whether the agent found the platform at boot. False means it was configured for one it did not find, and it produces no evidence."
        },
        "platformVersion": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "description": "The platform's own version string, when it reports one. Informational."
        },
        "ext": {
          "$ref": "#/$defs/Ext",
          "description": "Ecosystem-defined extension members per SPEC.md §4.5.1."
        }
      }
    },
    "Ext": {
      "title": "Ext",
      "description": "Vendor-namespaced extension object per SPEC.md §4.5.1. Each immediate key MUST be a reverse-DNS namespace; structure under each namespace is opaque to the framework.",
      "type": "object",
      "minProperties": 1,
      "additionalProperties": true,
      "propertyNames": {
        "pattern": "^[a-z][a-z0-9-]*(\\.[a-z0-9-]+)+$"
      }
    }
  }
} as const;

/** As {@link PAYLOAD_SCHEMA}, for the success-response variant. */
export const RESPONSE_PAYLOAD_SCHEMA = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$ref": "#/$defs/Response",
  "$defs": {
    "Response": {
      "$anchor": "response",
      "title": "VTA Attestation Status — response payload",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "teeType",
        "detected"
      ],
      "properties": {
        "teeType": {
          "type": "string",
          "enum": [
            "nitro",
            "sev-snp",
            "simulated"
          ],
          "description": "The platform whose evidence vta/attestation/report returns: nitro (AWS Nitro Enclaves), sev-snp (AMD SEV-SNP), or simulated (a development build whose evidence no verifier should accept)."
        },
        "detected": {
          "type": "boolean",
          "description": "Whether the agent found the platform at boot. False means it was configured for one it did not find, and it produces no evidence."
        },
        "platformVersion": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "description": "The platform's own version string, when it reports one. Informational."
        },
        "ext": {
          "$ref": "#/$defs/Ext",
          "description": "Ecosystem-defined extension members per SPEC.md §4.5.1."
        }
      }
    },
    "Ext": {
      "title": "Ext",
      "description": "Vendor-namespaced extension object per SPEC.md §4.5.1. Each immediate key MUST be a reverse-DNS namespace; structure under each namespace is opaque to the framework.",
      "type": "object",
      "minProperties": 1,
      "additionalProperties": true,
      "propertyNames": {
        "pattern": "^[a-z][a-z0-9-]*(\\.[a-z0-9-]+)+$"
      }
    }
  }
} as const;

/**
 * SPEC.md §7.2 policy for the request variant, from this specification's
 * front matter. Pass to `consumeInbound` — items 5b, 7 and 8 are
 * per-specification and cannot be derived from the document alone, and
 * item 2 needs the schema this carries.
 */
export const SPEC = {
  typeUri: TYPE_URI,
  isBearer: false,
  isProofRequired: false,
  isRecipientRequired: true,
  isIssuedAtRequired: false,
  payloadSchema: PAYLOAD_SCHEMA,
} as const;

/**
 * SPEC.md §7.2 policy for the success-response variant. `isRecipientRequired`
 * tracks the *issuer* party's requirement because a response swaps the
 * parties (§7.3 item 5).
 */
export const RESPONSE_SPEC = {
  typeUri: RESPONSE_TYPE_URI,
  isBearer: false,
  isProofRequired: true,
  isRecipientRequired: true,
  isIssuedAtRequired: false,
  payloadSchema: RESPONSE_PAYLOAD_SCHEMA,
} as const;
